// Data Top Destination In Indonesia
const destinations = [
  {
    id: 1,
    name: 'Bali',
    location: 'Bali',
    description: 'Pulau dengan keindahan alam dan budaya yang kaya.',
    score: 9.5,
  },
  {
    id: 2,
    name: 'Borobudur',
    location: 'Magelang, Jawa Tengah',
    description: 'Candi Buddha terbesar di dunia.',
    score: 9.2,
  },
  {
    id: 3,
    name: 'Raja Ampat',
    location: 'Papua Barat',
    description: 'Destinasi sidrkeling dan diving terbaik di dunia.',
    score: 9.7,
  },
  {
    id: 4,
    name: 'Bromo',
    location: 'Malang, Jawa Timur',
    description: 'Gunung berapi yang menawarkan pemandangan matahari terbit yang memukau.',
    score: 9.0,
  },
  {
    id: 5,
    name: 'Tanjung Puting',
    location: 'Kalimantan Tengah',
    description: 'Habitat asli orangutan dan berbagai satwa liar lainnya.',
    score: 9.3,
  },
  {
    id: 6,
    name: 'Labuan Bajo',
    location: 'Nusa Tenggara Timur',
    description: 'Gerbang menuju Taman Nasional Komodo.',
    score: 9.1,
  },
  {
    id: 7,
    name: 'Yogyakarta',
    location: 'Yogyakarta',
    description: 'Kota yang kaya akan seni dan budaya.',
    score: 8.8,
  },
  {
    id: 8,
    name: 'Tana Toraja',
    location: 'Sulawesi Selatan',
    description: 'Destinasi wisata budaya dengan tradisi unik dan keindahan alam yang menakjubkan.',
    score: 9.4,
  },
  {
    id: 9,
    name: 'Lombok',
    location: 'Nusa Tenggara Barat',
    description: 'Pulau dengan pantai indah dan Gunung Rinjani sebagai daya tarik utama.',
    score: 9.0,
  },
  {
    id: 10,
    name: 'Manado',
    location: 'Sulawesi Utara',
    description: 'Kota dengan keindahan bawah laut yang menakjubkan.',
    score: 8.9,
  },
  {
    id: 11,
    name: 'Derawan',
    location: 'Kalimantan Timur',
    description: 'Pulau dengan pantai berpasir putih dan terumbu karang yang indah.',
    score: 9.2,
  },
  {
    id: 12,
    name: 'Belitung',
    location: 'Kepulauan Bangka Belitung',
    description: 'Pulau dengan pantai yang dihiasi batu granit raksasa.',
    score: 8.7,
  },
  {
    id: 13,
    name: 'Dieng',
    location: 'Banjarnegara, Jawa Tengah',
    description: 'Destinasi wisata pegunungan dengan pesona alam yang menakjubkan.',
    score: 8.5,
  },
  {
    id: 14,
    name: 'Pulau Komodo',
    location: 'Nusa Tenggara Timur',
    description: 'Pulau dengan habitat asli Komodo, reptil terbesar di dunia.',
    score: 9.6,
  },
  {
    id: 15,
    name: 'Toba',
    location: 'Sumatera Utara',
    description: 'Danau vulkanik terbesar di Indonesia.',
    score: 8.9,
  },
  {
    id: 16,
    name: 'Bukit Lawang',
    location: 'Sumatera Utara',
    description: 'Destinasi wisata untuk menyaksikan orangutan di habitat aslinya.',
    score: 8.6,
  },
  {
    id: 17,
    name: 'Gunung Rinjani',
    location: 'Lombok, Nusa Tenggara Barat',
    description: 'Gunung tertinggi kedua di Indonesia dengan pemandangan yang spektakuler.',
    score: 9.0,
  },
  {
    id: 18,
    name: 'Pulau Seribu',
    location: 'Kepulauan Seribu, Jakarta',
    description: 'Gugusan pulau-pulau di dekat Jakarta yang menawarkan keindahan bawah laut.',
    score: 8.8,
  },
  {
    id: 19,
    name: 'Ubud',
    location: 'Bali',
    description: 'Kota seni dan budaya di Bali dengan pemandangan alam yang menakjubkan.',
    score: 9.1,
  },
  {
    id: 20,
    name: 'Pulau Weh',
    location: 'Aceh',
    description: 'Pulau dengan keindahan bawah laut yang luar biasa.',
    score: 8.7,
  },
  {
    id: 21,
    name: 'Tanjung Lesung',
    location: 'Banten',
    description: 'Destinasi wisata pantai dengan paidrama yang indah dan berbagai aktivitas laut.',
    score: 8.5,
  },
  {
    id: 22,
    name: 'Pulau Morotai',
    location: 'Maluku Utara',
    description: 'Pulau dengan pantai indah dan tempat menyelam yang menakjubkan.',
    score: 8.9,
  },
  {
    id: 23,
    name: 'Lengkuas Island',
    location: 'Belitung',
    description: 'Pulau kecil dengan mercusuar bersejarah dan pantai pasir putih.',
    score: 9.3,
  },
  {
    id: 24,
    name: 'Pantai Pink',
    location: 'Labuan Bajo, Nusa Tenggara Timur',
    description: 'Pantai dengan pasir berwarna pink yang langka.',
    score: 9.4,
  },
  {
    id: 25,
    name: 'Bunaken',
    location: 'Sulawesi Utara',
    description: 'Destinasi wisata menyelam yang terkenal dengan keanekaragaman biota lautnya.',
    score: 9.2,
  },
];

export default destinations;
